redis:
  image: redis:3.2
  expose:
    - 6379
db:
  image: mariadb:10.3
  restart: always
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: db
    MYSQL_USER: admin
    MYSQL_PASSWORD: pass

web:
  image: dimaip/docker-neos-alpine:latest
  hostname: 'sfiru'
  ports:
    - '80'
    - '1122:22'
  links:
    - redis:redis
    - db:db
  volumes:
    - /data
    - ./Persistent:/data/shared/Data/Persistent
    - ./Settings.yaml:/data/shared/Configuration/Settings.yaml
  environment:
    - VIRTUAL_HOST=sfi.ru,www.sfi.ru,dev.sfi.ru,next.sfi.ru
    - REPOSITORY_URL=https://github.com/sfi-ru/SfiDistr
    - LETSENCRYPT_HOST=sfi.ru,www.sfi.ru
    - LETSENCRYPT_EMAIL=dimaip@gmail.com
    - IMPORT_GITHUB_PUB_KEYS=dimaip
    - PHP_TIMEZONE=Europe/Moscow
    - AWS_ENDPOINT=https://hb.bizmrg.com
    - AWS_BACKUP_ARN=s3://psmb-neos-resources/db/sfi/
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
