
Neos:
  Flow:
    mvc:
      routes:
        'Sfi.Sber':
          position: 'before Neos.Neos'

Sfi:
  Sber:
    options:
      endpointUrl: 'https://securepayments.sberbank.ru/payment/rest/register.do'
      returnUrl: 'https://sfi.ru/support/thanks.html'
      #endpointUrl: 'https://3dsec.sberbank.ru/payment/rest/register.do'
      #userName: 'username'
      #password: 'password'
