
Neos:
  Neos:
    typoScript:
      autoInclude:
        Sfi.Shared: true
    nodeTypes:
      groups:
        contentElements:
          position: 105
          label: 'Элемент контента'
        contentBlocks:
          position: 110
          label: 'Блоки контента'
        structure:
          position: 115
          label: Структура
        contentWidgets:
          position: 120
          label: Виджеты
        lists:
          position: 130
          label: Списки
        system:
          position: end
          label: Системные
  Fusion:
    defaultContext:
      NodeTypeConfiguration: Sfi\Shared\TypoScript\Eel\Helper\NodeTypeConfigurationHelper
