Neos:
  GoogleAnalytics:
    authentication:
      applicationName: 'Neos GA'
      clientId: '4730774009-h57rl51jmjbrljt2mii1ebn74a8hsrr3.apps.googleusercontent.com'
      clientSecret: '%env:GA_SECRET%'
      developerKey: '%env:GA_DEVKEY%'
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'email-smtp.us-west-2.amazonaws.com'
        port: '465'
        encryption: 'ssl'
        username: 'AKIAIV3MQACBKVT236RA'
        password: '%env:SFI_SES_PASSWORD%'
  Flow:
    http:
      baseUri: 'https://sfi.ru/'
    log:
      systemLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      securityLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      sqlLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      i18nLogger:
        backend: Yeebase\Graylog\Log\Backend\GraylogBackend
    error:
      exceptionHandler:
        className: 'Yeebase\Graylog\Error\GraylogExceptionHandler'
