dbdata:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /var/lib/mysql

redis:
  image: redis

db:
  image: tutum/mariadb:latest
  expose:
    - 3306
  volumes_from:
    - dbdata
  environment:
    MARIADB_PASS: pass

webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
    - /data
    - /tmp
    - Persistent:/data/www/sfi.ru/surf/shared/Data/Persistent
    - /etc/localtime:/etc/localtime:ro

web:
  image: dimaip/sfidistr:latest
  ports:
    - '80'
  links:
    - db:db
    - redis
  volumes_from:
    - webdata
  environment:
    VIRTUAL_HOST: 'sfi.ru,dev.sfi.ru,next.sfi.ru,direct.sfi.ru'
    T3APP_NAME: 'sfi.ru'
    T3APP_BUILD_REPO_URL: 'https://github.com/sfi-ru/SfiDistr.git'

ssh:
  image: million12/php-app-ssh
  ports:
    - '1122:22'
  links:
    - db:db
    - redis
    - web:web
  volumes_from:
    - webdata
  environment:
    IMPORT_GITHUB_PUB_KEYS: dimaip

sshresources:
  image: million12/php-app-ssh
  ports:
    - '2222:22'
  volumes:
    - Persistent:/data/www/sfi.ru/surf/shared/Data/Persistent
  environment:
    IMPORT_GITHUB_PUB_KEYS: dimaip
