
Sfi:
  News:
    listNode:
      numberOfItems: 10000
      paginationEnabled: false
      pagination:
        itemsPerPage: 24
        maximumNumberOfLinks: 15
      itemRenderer: ''
      listTitle: ''
      listTitleClass: ''
      class: 'medium-block-grid-2 small-block-grid-1'
      itemClass: ''
      archiveLink: ''
    newsArchive:
      numberOfItems: 10000
      paginationEnabled: true
      pagination:
        itemsPerPage: 24
        maximumNumberOfLinks: 15
      listTitle: ''
      listTitleClass: SectionDivider--Service
      class: 'large-block-grid-3 medium-block-grid-2 small-block-grid-1'
      dataColumns: true
      itemClass: ''
      archiveLink: ''
      showOnlyNews: false
      layout: ContentDefault
    publishedBooksArchive:
      numberOfItems: 10000
      paginationEnabled: true
      pagination:
        itemsPerPage: 24
        maximumNumberOfLinks: 15
      listTitle: ''
      listTitleClass: PageTitle
      class: 'medium-block-grid-2 small-block-grid-1'
      dataColumns: false
      itemClass: ''
      archiveLink: ''
      showOnlyNews: false
      layout: ContentWithSidebar
    articlesList:
      numberOfItems: 100
      pagination: null
      listTitle: ''
      listTitleClass: 'H3 textAlign-center'
      class: ''
      archiveLink: ''
    newsLatest:
      numberOfItems: 6
      pagination: null
      listTitle: newsLatest.listTitle
      listTitleClass: SectionDivider--Service
      class: 'NewsLatest-Grid medium-block-grid-2 small-block-grid-1'
      wrapClass: NewsLatest
      archiveLink: ~/sfi-today
      archiveLinkTitle: newsLatest.archiveLinkTitle
    newsRelated:
      numberOfItems: 4
      listTitle: ''
      class: ''
      archiveLink: ~/sfi-today
      archiveLinkTitle: newsLatest.archiveLinkTitle
      thumbnailWidth: 100
      thumbnailHeight: 100
      dateFormat: 'dd MMMM yyyy'
    newsShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: 'dd MMMM yyyy'
    newsDetail:
      dateFormat: 'dd MMMM yyyy'
    announcementsList:
      numberOfItems: 6
      pagination: null
      listTitle: news.announcements
      listTitleClass: SectionDivider--Service
      class: ''
      archiveLink: ''
    announcementShort:
      thumbnailWidth: 420
      thumbnailHeight: 222
      dateFormat: ''
    announcementDetail:
      dateFormat: 'dd MMMM yyyy HH:mm'
    topList:
      numberOfItems: 3
      listTitle: null
      class: 'Carousel--Cover js-carousel-1x'
      archiveLink: ''
    topShort:
      thumbnailWidth: 1200
      thumbnailHeight: 400
      dateFormat: d.MM
    listByTag:
      numberOfItems: 10000
      paginationEnabled: true
      pagination:
        itemsPerPage: 24
        maximumNumberOfLinks: 15
      listTitle: listByTag.archiveLinkTitle
      listTitleClass: SectionDivider--Service
      class: 'medium-block-grid-2 small-block-grid-1'
      archiveLink: ''
Neos:
  Neos:
    nodeTypes:
      groups:
        news:
          position: end
          label: News
    fusion:
      autoInclude:
        Sfi.News: true
  Fusion:
    defaultContext:
      NewsConfiguration: Sfi\News\TypoScript\Eel\Helper\ConfigurationHelper
