
Sfi:
  Sfi:
    apiAuth: '%env:SFI_API_AUTH%'
    viewHelpers:
      partialRootPath: 'resource://Sfi.Sfi/Private/Partials/'
Psmb:
  Newsletter:
    globalSettings:
      senderAddress: no-reply@sfi.ru
      senderName: SFI.ru
    subscriptions:
      -
        identifier: instant_ru
        renderer: 'Sfi.Sfi:InstantMail'
        sendFromUiNodeType: 'Sfi.News:News'
        showInSubscribe: true
        label: 'Мгновенное уведомление'
        description: 'Получать полные версии статей как только они опубликованы'
        interval: manual
        senderName: 'СФИ'
        dimensions:
          language:
            - ru
      -
        identifier: digest_ru
        renderer: 'Sfi.Sfi:NewsletterMail'
        sendFromUiNodeType: 'Sfi.Sfi:Newsletter'
        showInSubscribe: true
        label: 'Авторский дайджест'
        description: 'Получать раз в две недели авторский обзор лучших публикаций'
        footerInfo: 'Вы получили это письмо, поскольку подписаны на Авторский обзор лучших публикаций сайта Свято-Филаретовского института. Дайджест приходит раз в две недели.'
        interval: manual
        senderName: 'СФИ'
        dimensions:
          language:
            - ru
      -
        identifier: instant_en
        renderer: 'Sfi.Sfi:InstantMail'
        sendFromUiNodeType: 'Sfi.News:News'
        showInSubscribe: true
        label: 'Instant Notification'
        description: 'Recevie full versions of articles as they are published'
        interval: manual
        senderName: 'SFI'
        dimensions:
          language:
            - en
      -
        identifier: digest_en
        renderer: 'Sfi.Sfi:DigestMail'
        sendFromUiNodeType: 'Sfi.Sfi:Newsletter'
        showInSubscribe: true
        label: 'Monthly Digest'
        description: 'Receive newsletter by Sofia Androsenko to your inbox'
        interval: manual
        senderName: 'SFI'
        dimensions:
          language:
            - en
      -
        identifier: datasource-chapel
        renderer: 'Sfi.Sfi:FundraisingMail'
        sendFromUiNodeType: 'Sfi.Sfi:AutomatedNewsletter'
        dataSourceIdentifier: 'Json'
        dataSourceOptions:
          uri: 'http://eventstore:2113/projection/datasource-chapel/result'
        label: 'Жертвователи на часовню с начала года'
        interval: manual
        senderName: 'Поддержать СФИ'
        replyToAddress: 'donate@sfi.ru'
        dimensions:
          language:
            - ru
      -
        identifier: fundraising_timed
        renderer: 'Sfi.Sfi:FundraisingMail'
        sendFromUiNodeType: 'Sfi.Sfi:AutomatedNewsletter'
        interval: manual
        senderName: 'Поддержать СФИ'
        replyToAddress: 'donate@sfi.ru'
        dimensions:
          language:
            - ru
Neos:
  Fusion:
    defaultContext:
      Sfi: Sfi\Sfi\Helper\SfiHelper
  Flow:
    mvc:
      routes:
        'Sfi.Sfi':
          position: 'before Neos.Neos'
    session:
      inactivityTimeout: 604800
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://dev.sfi.ru/'
    resource:
      collections:
        persistent:
          storage: s3PersistentResourcesStorage
          target: s3PersistentResourcesTarget
      storages:
        s3PersistentResourcesStorage:
          storage: 'Flownative\Aws\S3\S3Storage'
          storageOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'storage/sfi/'
      targets:
        s3PersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'target/sfi/'
            baseUri: 'https://psmb-neos-resources.hb.bizmrg.com/target/sfi/'
  Neos:
    Ui:
      resources:
        javascript:
          'Sfi.Sfi:Itemprop':
            resource: '${"resource://Sfi.Sfi/Public/JavaScript/Itemprop/Plugin.js"}'
      frontendConfiguration:
        defaultInlineEditor: 'ckeditor5'
    userInterface:
      loadMinifiedJavascript: false
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          title: Print
          position: 200
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
          presets:
            default:
              baseNodeType: 'Neos.Neos:Document,!Sfi.News:News'
    nodeTypes:
      groups:
        contentBlocks:
          position: 110
          label: 'Content Blocks'
    fusion:
      autoInclude:
        Sfi.Sfi: true
  ContentRepository:
    contentDimensions:
      language:
        default: ru
        defaultPreset: ru
        label: Language
        icon: icon-language
        presets:
          ru:
            label: Russian
            values:
              - ru
            uriSegment: ''
          en:
            label: English
            values:
              - en
            uriSegment: en
  GoogleAnalytics:
    stats:
      uniquePageviewsBySource:
        metrics: 'ga:uniquePageviews'
        dimensions: 'ga:source'
        sort: '-ga:uniquePageviews'
        max-results: 25
  SwiftMailer:
    transport:
      type: 'Neos\SwiftMailer\Transport\LoggingTransport'
Yeebase:
  Graylog:
    host: 'graylog'
    port: 12201
    chunksize: 'wan'
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: '%env:AWS_ACCESS_KEY_ID%'
            secret: '%env:AWS_SECRET_ACCESS_KEY%'
          endpoint: 'https://hb.bizmrg.com'
