
Sfi:
  Sfi:
    viewHelpers:
      partialRootPath: 'resource://Sfi.Sfi/Private/Partials/'
Psmb:
  Newsletter:
    globalSettings:
      senderAddress: no-reply@sfi.ru
      senderName: SFI.ru
    subscriptions:
      -
        identifier: instant_ru
        renderer: 'Sfi.Sfi:InstantMail'
        sendFromUiNodeType: 'Sfi.News:News'
        label: 'Мгновенное уведомление'
        description: 'Получать полные версии статей как только они опубликованы'
        interval: manual
        senderName: 'СФИ'
        dimensions:
          language:
            - ru
      -
        identifier: digest_ru
        renderer: 'Sfi.Sfi:NewsletterMail'
        sendFromUiNodeType: 'Sfi.Sfi:Newsletter'
        label: 'Авторский дайджест'
        description: 'Получать раз в две недели авторский обзор лучших публикаций'
        footerInfo: 'Вы получили это письмо, поскольку подписаны на Авторский обзор лучших публикаций сайта Свято-Филаретовского института. Дайджест приходит раз в две недели.'
        interval: manual
        senderName: 'СФИ'
        dimensions:
          language:
            - ru
      -
        identifier: instant_en
        renderer: 'Sfi.Sfi:InstantMail'
        sendFromUiNodeType: 'Sfi.News:News'
        label: 'Instant Notification'
        description: 'Recevie full versions of articles as they are published'
        interval: manual
        senderName: 'SFI'
        dimensions:
          language:
            - en
      -
        identifier: digest_en
        renderer: 'Sfi.Sfi:DigestMail'
        sendFromUiNodeType: 'Sfi.Sfi:Newsletter'
        label: 'Monthly Digest'
        description: 'Receive newsletter by Sofia Androsenko to your inbox'
        interval: manual
        senderName: 'SFI'
        dimensions:
          language:
            - en
Neos:
  Flow:
    session:
      inactivityTimeout: 604800
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://sfi.ru/'
  Neos:
    userInterface:
      loadMinifiedJavascript: false
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          title: Print
          position: 200
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
    nodeTypes:
      groups:
        contentBlocks:
          position: 110
          label: 'Content Blocks'
    fusion:
      autoInclude:
        Sfi.Sfi: true
  ContentRepository:
    contentDimensions:
      language:
        default: ru
        defaultPreset: ru
        label: Language
        icon: icon-language
        presets:
          ru:
            label: Russian
            values:
              - ru
            uriSegment: ''
          en:
            label: English
            values:
              - en
            uriSegment: en
